### ISSUE TITLE
Having issues with cython build command

### ISSUE THREAD

**Issue by ApurvaMisra** [mike-huls/cythonbuilder#3]
Cython version 0.29.33 Python 3.7.2 on Windows 10 system

I get this error whenever I run Cython builder command in the terminal
  _File "c:\python37\lib\site-packages\cythonbuilder\__init__.py", line 2, in <module>
    from cythonbuilder.cython_builder import cy_init, cy_clean, cy_build, cy_list, cy_interface
  File "c:\python37\lib\site-packages\cythonbuilder\cython_builder.py", line 9, in <module>
    from cythonbuilder import pyigenerator
  File "<fstring>", line 1
    (argument=)
             ^
SyntaxError: invalid syntax_
![image](https://user-images.githubusercontent.com/22544948/218328153-d2720047-98f2-4d36-adf2-8b9179ea8055.png)

**Comment by mike-huls** [comment]
Fixed in the newest version of CythonBuilder! v0.1.15.
Thanks for reporting the issue

kind regards,


mike
