### ISSUE TITLE
[bug] generating pyi file decode errors

### ISSUE THREAD

**Issue by buzMartin** [mike-huls/cythonbuilder#4]
I have got this error while generating pyi file.

[cythonbuilder] [build] build error: 'gbk' codec can't decode byte 0xaf in position 1204: illegal multibyte sequence

I think the reason might be that there are some chinese characters in my code.

I have add parameter "encoding='utf-8'" to all open() function in pyigenerator.py to fix this problem.

I'm not sure if it's the only way to fix this problem, if so, please consider to add a encoding switch in cli to avoid changing the source code, thanks!

**Comment by mike-huls** [comment]
Fixed in the newest version of CythonBuilder! v0.1.15.
Thanks for reporting the issue.

I've also upgraded the CLI so check out `cybuilder --help` after upgrading

kind regards,


mike
