### ISSUE TITLE
Cannot generate pyi correctly for Cython enum

### ISSUE THREAD

**Issue by buzMartin** [mike-huls/cythonbuilder#6]
for example, the following code:
`cpdef enum PluginType:
    PY
    PYD
`
This will generate a pyi like below:
`def enum PluginType:
 ...`
But it's cannot be used in IDE.
Maybe it should generate something like this:
`class PluginType:
    PY=...
    PYD=...
`

**Comment by buzMartin** [comment]
Maybe better generate like below:
from enum import Enum
class PluginType(Enum):
    PY=...
    PYD=...

**Comment by mike-huls** [comment]
Hello @buzMartin. Thanks for your message, I'll start looking into it!

**Comment by mike-huls** [comment]
@buzMartin 
I've added support for enums. Let me know what you think!

**Comment by buzMartin** [comment]
I have tried and that's great, but I have found a bug for the generation. Maybe I should open another issue.
If the file only contains a enum and __name__=="__main__", the generated pyi file will also contains __name__=="__main__".
cy_cnum.pyx file
`from enum import Enum
class NewEnum(Enum):
    a = 1
    b = 2
if __name__=="__main__":
    print(NewEnum.a.value)`
The generated cy_cnum.pyi is:
`from enum import Enum
class NewEnum(Enum):
    a = 1
    b = 2
if __name__=="__main__":
    print(NewEnum.a.value)`

**Comment by mike-huls** [comment]
Hello @buzMartin 
Great find, i've fixed that too in version 0.1.17!
