### ISSUE TITLE
some error for first time user

### ISSUE THREAD

**Issue by chasezheng** [mike-huls/cythonbuilder#8]
great tool, thanks for working on this

I see some error, trying to run this in a fresh env.

In __main__.py, I need to change to "from .cli import app", which is a relative import, in order to fix a import error.

Also, coloredlogs is a dependency which is not listed.

I am using version 0.1.19

**Comment by mike-huls** [comment]
Hello @chasezheng , thanks for the feedback. I've fixed these issues in v0.1.20 which is ready to install now!
